# Generated by Django 2.1.7 on 2019-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aPersonName', models.CharField(max_length=200)),
                ('bPersonName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bPersonName', models.CharField(max_length=200)),
                ('generatedPassWord', models.CharField(max_length=200)),
            ],
        ),
    ]
