# Generated by Django 2.1.7 on 2019-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablea',
            old_name='bPersonName',
            new_name='aPersonSurname',
        ),
        migrations.AddField(
            model_name='tableb',
            name='bPersonSurname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
